modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
issueTrackerURL=""
[[mods]]
modId="nomorenbt"
version="${file.jarVersion}"
displayName="No More NBT"
displayURL=""
logoFile="nomorenbt.png"
credits=""
authors="Azures"
description='''
An libs for have alternative to NBT Data
'''
[[dependencies.nomorenbt]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.nomorenbt]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
